apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r4kwsp1yj-nodejs 
  janus-idp.io/tekton: r4kwsp1yj-nodejs
  backstage.io/kubernetes-id: r4kwsp1yj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r4kwsp1yj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  